### ISSUE TITLE
There's no limits to the period key

### ISSUE THREAD

**Issue by AustinTSchaffer** [t-eckert/react-rpn#4]
There's no limits to the period key. Also, the values with extraneous periods will be parsed by the calculator. It almost looks like the values will be parsed up until the second period. In the example image, the result of adding `2....etc...0` and `1.2..3...etc` is `3.2`.

It seems like there needs to be an additional check on the user's input that takes the current state into consideration, such as a count of the dot characters or a boolean flag that keeps track of the "dot state" of the current value.

![image](https://user-images.githubusercontent.com/16184219/36601734-dcc216b0-1883-11e8-8bf6-fe89ffa47c8b.png)

**Comment by t-eckert** [comment]
Added a check to make sure only one decimal point allowed.

```
decimalToInputActive = () => {
  const stackVals = this.state.stack
  let inputActive = stackVals[0]
  inputActive = inputActive.toString()
  if (inputActive.includes('.')) {
    console.log("A . is already in the display.")
  }
  else {
     inputActive = inputActive +'.'
     this.setState({stack: [inputActive,...stackVals.slice(1)]})
     console.log(inputActive)
   } 
}
```
