### ISSUE TITLE
Not very mobile friendly

### ISSUE THREAD

**Issue by AustinTSchaffer** [t-eckert/react-rpn#5]
![41010859-8c86-4ae8-a8f0-9f7b936a7288](https://user-images.githubusercontent.com/16184219/36633038-6e8bc748-195c-11e8-81e9-8be0140114d5.png)

This screencap was taken on an iPhone 6.

**Comment by t-eckert** [comment]
Below 570px width, the functions now switch to a vertical format: 
<img width="512" alt="screen shot 2018-03-05 at 6 13 09 pm" src="https://user-images.githubusercontent.com/29112081/37010568-0646ab84-20a1-11e8-9405-d970f1191b2f.png">
